# To understand user defined variables

name: User Defined Variable Demo

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
env:
 firstName: Parameswari
 lastName: Bala
 
# Read User Defined Variables from environment
jobs:
 windows-job:
   runs-on: windows-latest
   steps:
     - name: Display env variables
       run: echo "Hi ${{firstName}}"
   
     
 ubuntu-job:
   runs-on: ubuntu-latest
   steps:
     - name: Display env variables
       run: echo "Hi ${{lastName}}"
   
   
   
   
